apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-service-ingress
  namespace: homework-ns
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /health/
        pathType: Prefix
        backend:
          service:
            name: kuber-service
            port:
              number: 80