apiVersion: v1
kind: Service
metadata:
  name: kuber-service
  namespace: homework-ns
spec:
  selector:
    app: http-service 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
      